# Generated by Django 5.1.3 on 2024-12-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryItem',
            new_name='Gallery',
        ),
    ]
